image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

.build-and-push:
  stage: build
  script:
    - if [ "${CI_COMMIT_REF_NAME}" = "master" ]; then TAG="latest"; else TAG="${CI_COMMIT_REF_NAME}"; fi
    - cd ${BUILD_PATH}
    - docker pull ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${TAG} || echo Existing image not available - starting from scratch
    - echo Quietly building ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${TAG}
#    - docker build -t ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:$CI_COMMIT_SHA -t ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${TAG} --cache-from ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${TAG} --quiet .
    - docker build -t ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${TAG} --cache-from ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${TAG} --quiet .
    - docker push ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}
  only:
    - master

build-iotcore:
  extends: .build-and-push
  variables:
    IMAGE_NAME: iotcore
    BUILD_PATH: ./iotplatform/iotcore/

build-elasticsearch:
  extends: .build-and-push
  variables:
    IMAGE_NAME: elasticsearch
    BUILD_PATH: ./iotplatform/elasticsearch/

build-mqtt-gateway-nodejs:
  extends: .build-and-push
  variables:
    IMAGE_NAME: mqtt-gateway-nodejs
    BUILD_PATH: ./iotplatform/mqtt-gateway-nodejs/

build-http-gateway-nodejs:
  extends: .build-and-push
  variables:
    IMAGE_NAME: http-gateway-nodejs
    BUILD_PATH: ./iotplatform/http-gateway-nodejs/

build-http-gateway-go:
  extends: .build-and-push
  variables:
    IMAGE_NAME: http-gateway-go
    BUILD_PATH: ./iotplatform/http-gateway-go/

build-ws-gateway-nodejs:
  extends: .build-and-push
  variables:
    IMAGE_NAME: ws-gateway-nodejs
    BUILD_PATH: ./iotplatform/ws-gateway-nodejs/

build-ws-gateway-go:
  extends: .build-and-push
  variables:
    IMAGE_NAME: ws-gateway-go
    BUILD_PATH: ./iotplatform/ws-gateway-go/

build-java-producer:
  extends: .build-and-push
  variables:
    IMAGE_NAME: java-producer
    BUILD_PATH: ./iotplatform/java-producer/

build-nodejs-producer:
  extends: .build-and-push
  variables:
    IMAGE_NAME: nodejs-producer
    BUILD_PATH: ./iotplatform/nodejs-producer/

build-python-producer:
  extends: .build-and-push
  variables:
    IMAGE_NAME: python-producer
    BUILD_PATH: ./iotplatform/python-producer/

build-redis:
  extends: .build-and-push
  variables:
    IMAGE_NAME: redis
    BUILD_PATH: ./iotplatform/redis/
