sudo: false
servies:
  - docker
language: python
branches:
  only:
  - master
git:
  submodules: false
  depth: 3
notifications:
  email: false
env:
  global:
    - BUILD_PATH=./iotplatform/iotcore/
    - DOCKERHUB_REPOSITORY=iotplatform
    - DOCKERHUB_USER=heldic
    - IMAGE_NAME=iotcore

script:
  - printenv | grep ".*DOCKERHUB.*"

before_install:
  - git config --global http.sslverify false
  - chmod +x -R travis

install:
  - source travis/check-live-deployment.sh
  - ./travis/check-live-deployment.sh

before_deploy:
  - docker --version
  - export CF_TRACE=false

deploy:
  - provider: script
    skip_cleanup: true
    script: travis/push-docker-images-to-dockerhub.sh
    on:
      tags: false
      #condition: $LIVE = true
