sudo: false
servies:
  - docker
cache:
  bundler: true
  directories:
    - $HOME/docker
language: python
branches:
  only:
  - master
git:
  submodules: false
  depth: 3
notifications:
  email: false
env:
  global:
    - DOCKERHUB_REPOSITORY=iotplatform
    - DOCKERHUB_USER=heldic

script:
  - printenv | grep ".*DOCKERHUB.*"

before_install:
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - git config --global http.sslverify false
  - chmod +x -R travis

install:
  - bundle install
  - source travis/check-live-deployment.sh
  - ./travis/check-live-deployment.sh

before_deploy:
  - docker --version
  - export CF_TRACE=false

deploy:
  - provider: script
    skip_cleanup: true
    script: env IMAGE_NAME=iotcore BUILD_PATH=./iotplatform/iotcore/ travis/push-docker-images-to-dockerhub.sh
    on:
      tags: false
      #condition: $LIVE = true

before_cache:
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
