apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: iot
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2022-01-24T07:18:38Z"
  labels:
    app: connect
    app.kubernetes.io/managed-by: Helm
    chart: iot-platform-0.1.0
    heritage: Helm
    release: iot
  name: iot-connect
  namespace: default
  resourceVersion: "82655"
  uid: e577b8b9-e733-4957-834f-9ae8fb1bdc31
spec:
  clusterIP: 10.110.136.167
  clusterIPs:
  - 10.110.136.167
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port-8083
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: connect
    release: iot
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
