apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: iot
    meta.helm.sh/release-namespace: default
  labels:
    app: mariadb
    app.kubernetes.io/managed-by: Helm
    chart: iot-platform-0.1.0
    heritage: Helm
    release: iot
  name: iot-mariadb
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb
    release: iot
  sessionAffinity: None
  type: ClusterIP