apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: iot
    meta.helm.sh/release-namespace: default
  generation: 1
  labels:
    app: mariadb
    app.kubernetes.io/managed-by: Helm
    chart: iot-platform-0.1.0
    heritage: Helm
    release: iot
  name: iot-mariadb
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mariadb
      release: iot
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mariadb
        release: iot
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: backend
        - name: MYSQL_PASSWORD
          value: qmJDiqlAr9Fcu5Rav0XJ
        - name: MYSQL_ROOT_PASSWORD
          value: mP6AMBTSSElsq1oQttZ1
        - name: MYSQL_USER
          value: backend
        image: mariadb:10
        imagePullPolicy: Always
        name: mariadb
        resources:
          requests:
            cpu: 5m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-persistent-storage
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gitlab-registry
      initContainers:
      - command:
        - chmod
        - -R
        - "777"
        - /var/lib/mysql
        image: busybox:1.27.2
        imagePullPolicy: IfNotPresent
        name: init-permission
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-persistent-storage
      - command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        image: busybox:1.27.2
        imagePullPolicy: IfNotPresent
        name: init-sysctl
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-claim