apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: iot
    meta.helm.sh/release-namespace: default
  generation: 1
  labels:
    app: kibana
    app.kubernetes.io/managed-by: Helm
    chart: iot-platform-0.1.0
    heritage: Helm
    release: iot
  name: iot-kibana
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kibana
      release: iot
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kibana
        release: iot
    spec:
      containers:
      - env:
        - name: CONSOLE_ENABLED
          value: "false"
        - name: ELASTICSEARCH_HOSTS
          value: http://iot-elasticsearch:9200
        - name: ELASTICSEARCH_PASSWORD
          value: CzJToWAkKYt4R71V7izW
        - name: ELASTICSEARCH_URL
          value: http://iot-elasticsearch:9200
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        image: kibana:6.8.8
        imagePullPolicy: Always
        name: kibana
        resources:
          requests:
            cpu: 5m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gitlab-registry
      initContainers:
      - command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        image: busybox:1.27.2
        imagePullPolicy: IfNotPresent
        name: init-sysctl
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30