apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: iot
    meta.helm.sh/release-namespace: default
  labels:
    app: connect
    app.kubernetes.io/managed-by: Helm
    chart: iot-platform-0.1.0
    heritage: Helm
    release: iot
  name: iot-connect
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port-8083
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: connect
    release: iot
  sessionAffinity: None
  type: ClusterIP