apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: iot
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2022-01-24T07:18:38Z"
  labels:
    app: elasticsearch
    app.kubernetes.io/managed-by: Helm
    chart: iot-platform-0.1.0
    heritage: Helm
    release: iot
  name: iot-elasticsearch
  namespace: default
  resourceVersion: "82642"
  uid: d6abd4f9-c00d-483e-b79a-8ecd94690aea
spec:
  clusterIP: 10.101.102.1
  clusterIPs:
  - 10.101.102.1
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port-9200
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: port-9300
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: elasticsearch
    release: iot
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
