version: '3.2'
services:
    nodejs-producer:
        build: ./nodejs-producer
        image: registry.gitlab.com/tum-iot-lab/iotplatform/nodejs-producer
        environment:
            MQTT_GATEWAY: ${PLATFORM_HOST}:1883
            IOTCORE_BACKEND: ${PLATFORM_HOST}:3000
            NAME: mqtt

    java-producer-go:
        build: ./java-producer
        image: registry.gitlab.com/tum-iot-lab/iotplatform/java-producer
        environment:
            HTTP_GATEWAY: ${PLATFORM_HOST}:8084
            IOTCORE_BACKEND: ${PLATFORM_HOST}:3000
            NAME: http-go

    java-producer-nodejs:
        build: ./java-producer
        image: registry.gitlab.com/tum-iot-lab/iotplatform/java-producer
        environment:
            HTTP_GATEWAY: ${PLATFORM_HOST}:8083
            IOTCORE_BACKEND: ${PLATFORM_HOST}:3000
            NAME: http-nodejs

    python-producer-nodejs:
        build: ./python-producer
        image: registry.gitlab.com/tum-iot-lab/iotplatform/python-producer
        environment:
            WS_GATEWAY: ${PLATFORM_HOST}:8765
            IOTCORE_BACKEND: ${PLATFORM_HOST}:3000
            NAME: ws-nodejs

    python-producer-go:
        build: ./python-producer
        image: registry.gitlab.com/tum-iot-lab/iotplatform/python-producer
        environment:
            WS_GATEWAY: ${PLATFORM_HOST}:8766
            IOTCORE_BACKEND: ${PLATFORM_HOST}:3000
            NAME: ws-go
