version: '3.6'
services:

  activemq:
    build: ./activemq
    ports:
      - "61616:61616"
      - "1883:1883"
      - "8161:8161"
      - "5672:5672"
    networks:
      - general

  nodejs_producer:
    depends_on:
      - activemq
    build: ./nodejs_producer
    networks:
      - general

  kafka:
    build: ./kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - general

  iotbridge:
    depends_on:
      - activemq
      - kafka
    build: ./iotbridge
    networks:
      - general

  flink:
    depends_on:
      - kafka
      - iotbridge
    build: ./flink
    ports:
      - "8081:8081"
    networks:
      - general

#   flink_jobmanager:
#     depends_on:
#       - kafka
#       - zookeeper
#       - iotbridge
#     image: flink
#     ports:
#       - "8081:8081"
#       - "6123:6123"
#     command: jobmanager
#     environment:
#       - JOB_MANAGER_RPC_ADDRESS=jobmanager
#     networks:
#       - general

#   flink_taskmanager:
#     depends_on:
#       - jobmanager
#     image: flink
#     ports:
#       - "6121:6121"
#       - "8081:8081"
#       - "6122:6122"
#     command: taskmanager
#     environment:
#       - JOB_MANAGER_RPC_ADDRESS=jobmanager
#     networks:
#       - general

#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
#     environment:
#       - cluster.name=docker-cluster
#       - bootstrap.memory_lock=true
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     volumes:
#       - esdata1:/usr/share/elasticsearch/data
#     ports:
#       - 9200:9200
#     networks:
#       - esnet
#       - general

#   elasticsearch2:
#     image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
#     environment:
#       - cluster.name=docker-cluster
#       - bootstrap.memory_lock=true
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#       - "discovery.zen.ping.unicast.hosts=elasticsearch"
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     volumes:
#       - esdata2:/usr/share/elasticsearch/data
#     networks:
#       - esnet
#       - general

#   kibana:
#     container_name: kibana
#     depends_on:
#       - elasticsearch1
#       - elasticsearch2
#     image: docker.elastic.co/kibana/kibana:6.2.4
#     networks:
#       - esnet
#       - general

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  general:
    driver: bridge
    ipam:
      driver: default
#  esnet:
