version: '3.6'
services:

  activemq:
    build: ./activemq
    ports:
      - "61616:61616"
      - "1883:1883"
      - "8161:8161"
      - "5672:5672"

  nodejs_producer:
    build: ./nodejs_producer

  java_producer:
    build: ./java_producer

  python_producer:
    build: ./python_producer

  iotcore:
    build: ./iotcore
    ports:
      - "8080:8080"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  iotbridge:
    build: ./iotbridge
    ports:
      - "8083:8083"
      - "8765:8765"

  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  flink:
    build: ./flink
    ports:
      - "8081:8081"

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"

  # kibana:
  #   depends_on:
  #     - elasticsearch
  #   build: ./kibana
  #   ports:
  #     - "5601:5601"
  #   networks:
  #     - general

networks:
  general:
    driver: bridge
    ipam:
      driver: default
