version: "3.2"
services:
  iotcore:
    build: ./iotcore
    image: registry.gitlab.com/vpacyna/iot-platform-slim/iotcore:microservice
    ports:
      - "3000:3000"
    environment:
      MARIADB: 10.156.0.8:3306
      KAFKA: 10.156.0.4:9092
      ZOOKEEPER: 10.156.0.9:2181
      ELASTICSEARCH: 10.156.0.7:9200
      ELASTICSEARCH_BIN_PORT: "9200"
      ELASTICSEARCH_USER: elastic
      ELASTICSEARCH_PASSWORD: CzJToWAkKYt4R71V7iz
      CONNECT: 10.156.0.6:8083
  http-gateway-nodejs:
    build: ./http-gateway-nodejs
    image: registry.gitlab.com/vpacyna/iot-platform-slim/http-gateway-nodejs:microservice
    environment:
      KAFKA: 10.156.0.16:9094
      ZOOKEEPER: 10.156.0.15:2181
    ports:
      - "8083:8083"
