apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: iot
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2022-01-24T07:18:37Z"
  labels:
    app: kafka
    app.kubernetes.io/managed-by: Helm
    chart: iot-platform-0.1.0
    heritage: Helm
    release: iot
  name: iot-kafka
  namespace: default
  resourceVersion: "82611"
  uid: ad8c4cfe-36cb-4610-a3e7-0cac595a66a0
spec:
  clusterIP: 10.108.74.153
  clusterIPs:
  - 10.108.74.153
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port-9092
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: port-9094
    port: 9094
    protocol: TCP
    targetPort: 9094
  selector:
    app: kafka
    release: iot
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}