apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
