name: Docker Image CI

on:
  push:
    branches: [ faas-ow-lrz-test ]
  pull_request:
    branches: [ faas-ow-lrz-test ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker images
      run: docker-compose build -f iotplatform/docker-compose.yml --parallel
    - name: push the Docker images
      run: docker-compose push -f iotplatform/docker-compose.yml
